--- 
version: "2"
services: 
  web:
    image: med_test
    build:
      context: .
      dockerfile: Dockerfile
    command: "bin/console server:run 0.0.0.0:8000"
    #depends_on:
    #  - "db"
    ports: 
      - "8000:8000"
    volumes: 
      - ".:/var/www/symfony"

  #db:
     #image: "mysql"
     #environment:
       #MYSQL_ALLOW_EMPTY_PASSWORD: example
       #MYSQL_DATABASE: symfony
     #ports:
           #- "3306:3306"