<?php

namespace SupportBundle\Repository;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends \Doctrine\ORM\EntityRepository
{
}
