<?php

namespace AppBundle\Repository;

/**
 * CallOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
