# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_EMPLOYEE:    ROLE_USER
        ROLE_ADMIN:       ROLE_EMPLOYEE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/(ru|uk)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ru|uk)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ru|uk)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }