sonata_admin:
    assets:
        extra_stylesheets: ['assets/style/admin.css']
        extra_javascripts: ['assets/javascript/admin.js']


sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        app.block.service.main: ~
        app.block.service.sections: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"