<?php

namespace ShowBundle\Repository;

/**
 * ShowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowsRepository extends \Doctrine\ORM\EntityRepository
{
}
