services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
        public: true

    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Page }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]


    sonata.block.service.main:
        class: AppBundle\Block\MainBlock
        arguments:
            - ~
            - '@templating.engine.twig'
        tags:
            - { name: sonata.block }
