services:

    app.block.service.main:
        class: AppBundle\Block\PageBlock
        arguments:
            - 'main_page_header'
            - '@templating.engine.twig'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sonata.block }

    app.block.service.sections:
        class: AppBundle\Block\SecondSectionsBlock
        arguments:
            - 'main_second_sections_block'
            - '@templating.engine.twig'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: sonata.block }

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }
        public: true

    app.admin.page:
        class: AppBundle\Admin\HeaderAdmin
        arguments: [~, AppBundle\Entity\Header, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Headers }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.admin.icon_block:
        class: AppBundle\Admin\IconBlockAdmin
        arguments: [~, AppBundle\Entity\IconBlock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: IconBlock, show_in_dashboard: false }
        public: false

    app.admin.second_section:
        class: AppBundle\Admin\SecondSectionAdmin
        arguments: [~, AppBundle\Entity\SecondSection, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SecondSection }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.admin.third_section:
        class: AppBundle\Admin\ThirdSectionAdmin
        arguments: [~, AppBundle\Entity\ThirdSection, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ThirdSection }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.admin.call_order:
        class: AppBundle\Admin\CallOrderAdmin
        arguments: [~, AppBundle\Entity\CallOrder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: orders, label: CallOrder }
        public: true

    app.admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Contact }
        public: true

    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [~, AppBundle\Entity\Service, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Service }
        public: true

    app.admin.icon_file_block:
        class: AppBundle\Admin\IconFileBlockAdmin
        arguments: [~, AppBundle\Entity\IconFileBlock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: IconFileBlock, show_in_dashboard: false  }
        public: true

    app.admin.our_works_category:
        class: AppBundle\Admin\OurWorksCategoryAdmin
        arguments: [~, AppBundle\Entity\OurWorksCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: OurWorksCategory }
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]
        public: true

    app.admin.our_works:
        class: AppBundle\Admin\OurWorksAdmin
        arguments: [~, AppBundle\Entity\OurWorks, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: OurWorks, show_in_dashboard: false }
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]
        public: true
