services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
        public: true

    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Page }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.admin.icon_block:
        class: AppBundle\Admin\IconBlockAdmin
        arguments: [~, AppBundle\Entity\IconBlock, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: IconBlock, show_in_dashboard: false }
        public: false

    app.admin.second_section:
        class: AppBundle\Admin\SecondSectionAdmin
        arguments: [~, AppBundle\Entity\SecondSection, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SecondSection }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.admin.third_section:
        class: AppBundle\Admin\ThirdSectionAdmin
        arguments: [~, AppBundle\Entity\ThirdSection, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ThirdSection }
        public: true
        calls:
            - [ setVichUploader, ['@vich_uploader.templating.helper.uploader_helper']]

    app.block.service.main:
        class: AppBundle\Block\MainBlock
        arguments:
            - ~
            - '@templating.engine.twig'
        tags:
            - { name: sonata.block }

    app.block.service.sections:
        class: AppBundle\Block\SectionsBlock
        arguments:
            - ~
            - '@templating.engine.twig'
        tags:
            - { name: sonata.block }

    app.admin.call_order:
        class: AppBundle\Admin\CallOrderAdmin
        arguments: [~, AppBundle\Entity\CallOrder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: orders, label: CallOrder }
        public: true
