liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        main_thumb :

            quality : 100

            filters :
                thumbnail  : { size : [555, 238], mode : outbound }