vich_uploader:
    db_driver: orm

    mappings:
        my_image:
            namer: Vich\UploaderBundle\Naming\HashNamer
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/web/images'

        my_doc:
            namer: Vich\UploaderBundle\Naming\HashNamer
            uri_prefix: /doc
            upload_destination: '%kernel.project_dir%/web/doc'